# Generated by Django 2.2.7 on 2019-11-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
    ]
